# Generated by Django 6.0.6 on 2026-07-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0002_chatlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatLog',
        ),
    ]
